import { contextBridge, ipcRenderer } from "electron";

/**
 * The trust boundary. The renderer runs sandboxed with context isolation on, so this file is the
 * only thing it can reach the main process through.
 *
 * Channel names are duplicated from `src/main/ipc.ts` on purpose: this side is generated by hand
 * so a change on either side fails to compile rather than silently no-op'ing at runtime.
 *
 * Every method returns plain, normalized data. The OAuth access token and refresh token are never
 * sent across this bridge under any circumstance.
 */

const CHANNELS = {
  getState: "widget:get-state",
  stateChanged: "widget:state-changed",
  refresh: "widget:refresh",
  resetAuth: "widget:reset-auth",
  dragStart: "widget:drag-start",
  dragMove: "widget:drag-move",
  dragEnd: "widget:drag-end",
  togglePanel: "widget:toggle-panel",
  hidePanel: "widget:hide-panel",
  setClickThrough: "widget:set-click-through",
  setWidgetVisible: "widget:set-widget-visible",
  setAutoLaunch: "widget:set-auto-launch",
  setRefreshInterval: "widget:set-refresh-interval",
  getStatusline: "widget:get-statusline",
  registerStatusline: "widget:register-statusline",
  unregisterStatusline: "widget:unregister-statusline",
  setNotifications: "widget:set-notifications",
  setCheckForUpdates: "widget:set-check-for-updates",
  openUpdatePage: "widget:open-update-page",
  openLogFolder: "widget:open-log-folder",
  openSettingsFolder: "widget:open-settings-folder",
  quit: "widget:quit",
} as const;

type Unsubscribe = () => void;

/** Strip the Electron event object; the renderer only ever wants the payload. */
function subscribe(channel: string, callback: (payload: unknown) => void): Unsubscribe {
  const listener = (_event: unknown, payload: unknown): void => callback(payload);
  ipcRenderer.on(channel, listener);
  return () => {
    ipcRenderer.removeListener(channel, listener);
  };
}

contextBridge.exposeInMainWorld("widgetApi", {
  getState: () => ipcRenderer.invoke(CHANNELS.getState),
  onState: (callback: (payload: unknown) => void) => subscribe(CHANNELS.stateChanged, callback),

  refresh: () => ipcRenderer.invoke(CHANNELS.refresh),
  resetAuth: () => ipcRenderer.invoke(CHANNELS.resetAuth),

  dragStart: () => ipcRenderer.invoke(CHANNELS.dragStart),
  dragMove: (x: number, y: number) => ipcRenderer.invoke(CHANNELS.dragMove, { x, y }),
  dragEnd: () => ipcRenderer.invoke(CHANNELS.dragEnd),

  togglePanel: () => ipcRenderer.invoke(CHANNELS.togglePanel),
  hidePanel: () => ipcRenderer.invoke(CHANNELS.hidePanel),

  setClickThrough: (enabled: boolean) => ipcRenderer.invoke(CHANNELS.setClickThrough, enabled),
  setWidgetVisible: (visible: boolean) => ipcRenderer.invoke(CHANNELS.setWidgetVisible, visible),
  setAutoLaunch: (enabled: boolean) => ipcRenderer.invoke(CHANNELS.setAutoLaunch, enabled),
  setRefreshInterval: (minutes: number) => ipcRenderer.invoke(CHANNELS.setRefreshInterval, minutes),

  getStatusline: () => ipcRenderer.invoke(CHANNELS.getStatusline),
  registerStatusline: () => ipcRenderer.invoke(CHANNELS.registerStatusline),
  unregisterStatusline: () => ipcRenderer.invoke(CHANNELS.unregisterStatusline),

  setNotifications: (enabled: boolean) => ipcRenderer.invoke(CHANNELS.setNotifications, enabled),
  setCheckForUpdates: (enabled: boolean) => ipcRenderer.invoke(CHANNELS.setCheckForUpdates, enabled),
  openUpdatePage: () => ipcRenderer.invoke(CHANNELS.openUpdatePage),
  openLogFolder: () => ipcRenderer.invoke(CHANNELS.openLogFolder),

  openSettingsFolder: () => ipcRenderer.invoke(CHANNELS.openSettingsFolder),
  quit: () => ipcRenderer.invoke(CHANNELS.quit),
});
